### ISSUE TITLE
Update API.md

### ISSUE THREAD

**Issue by GretaCB** [mapbox/vtshaver#10]
The README currently includes API docs, but there's also `make docs` which will automatically generate them and add them to `API.md`. It is currently still made up of node-cpp-skel API docs. 

### Next steps
- [x] Update code comments to reflect updated API ([see here](https://github.com/mapbox/vtshaver/blob/da0b5bad9bcf08368f47cb97081cd2917bdfab0d/src/shave.cpp#L31-L50)). You can use the examples in `README.md` as reference.
- [x] Update `filter` instantiation API docs to properly reflect creating the filter object. They are a little out of date.
  
Old:
```
var filters = shaver.styleToFilters(style);
```
  Now:
```
var filters = new shaver.Filters(shaver.styleToFilters(JSON.parse(style)));
```
- [x] Run [`make docs`](https://github.com/mapbox/vtshaver#docs) to generate new docs using [documentation.js](http://documentation.js.org/)
- [x] Potentially remove the API examples from the readme and just point to API.md?

cc @mapbox/maps-api

**Comment by springmeyer** [comment]
@zmofei I just noticed this issue after you fixed https://github.com/mapbox/vtshaver/pull/17. Looks like you've handled one aspect of this issue already. The next would be to:

 - Run `make docs`
 - That should overwrite `API.md` which is incorrect and still represents https://github.com/mapbox/node-cpp-skel
 - Remove the examples from the main README.md and link to API.md

Note: I see a typo that will break `make docs` that needs fixed:

```js
    "docs": "npm install documentation@^4.0.0-beta5 --no-save && documentation build src/*.cpp --polyglot -f md -o API.md"
```

**Comment by zmofei** [comment]
I have done the 2nd and 3rd step, but after checked the `API.md` I realized the comments need to revise carefully(some mistakes and do not have the Javascript parts API). I will request another PR after I update the comments and the readme.

**Comment by springmeyer** [comment]
> I will request another PR after I update the comments and the readme.

👍 Thanks!
