### ISSUE TITLE
Add CLI tests

### ISSUE THREAD

**Issue by GretaCB** [mapbox/vtshaver#14]
The CLI could use some tests

### Next Actions
- [ ] Update `bin/vtshave.js` to [accept a `--filter` parameter](https://github.com/mapbox/vtshaver/issues/13), which will be a `new Shaver.Filter` object.
- [ ] Create `test/cli.test.js` and add unit tests for `bin/vtshave.js` (See [vtvalidate's CLI tests](https://github.com/mapbox/vtvalidate/blob/master/test/cli.test.js) for reference)

**Comment by springmeyer** [comment]
Now done in https://github.com/mapbox/vtshaver/commit/6b0e779b0109665df1f4257ff710825789ed7d02#diff-da8fe3f2391da380ddef00afcc0f93f0
