### ISSUE TITLE
Use Nan::AsyncWorker

### ISSUE THREAD

**Issue by GretaCB** [mapbox/vtshaver#4]
Per @alliecrevier 's thoughts:

 - [ ] Replace `AsyncBaton` and `AfterShave` (the name is so good so try to figure out a way to keep it going) with a `Nan::AsyncWorker` subclass and `Nan::AsyncQueueWorker`
 - [ ] Make sure this fixes deprecation warnings related to the use of `MakeCallback` and `Call`

Ref: https://github.com/mapbox/vtcomposite/issues/52, in particular
> - [ ] Make code changes to fix the deprecation warnings related to the use of MakeCallback and Call. Example PR to follow: https://github.com/mapbox/node-cpp-skel/pull/127/files

**Comment by springmeyer** [comment]
Porting to NAPI will supercede this: #22
