### ISSUE TITLE
Handling Expressions that fail during evaluation

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtshaver#45]
Expression evaluation in gl-native may fail, returning `EvaluationError` type, like [here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/expression/assertion.cpp#L98-L103).

Currently, if this happens, `false` will be returned from [this vtshaver code](https://github.com/mapbox/vtshaver/blob/b0d8eb414eda21f6735228d144327e4f79b9e87d/src/shave.cpp#L304). The impact of that could be that whole features are dropped even if all of the other conditions of the filter evaluate to `true`.

Possible solutions are:

 - Detect expression errors and warn, while continuing to discard the feature
 - Keep features in this case
 - Throw an error in this case

It's hard to know which is better.

**Comment by springmeyer** [comment]
Initial fix appears to be working:

```diff
--- a/src/shave.cpp
+++ b/src/shave.cpp
@@ -21,6 +21,7 @@
 #include <vtzero/index.hpp>
 #include <vtzero/property_mapper.hpp>
 #include <vtzero/vector_tile.hpp>
+#include <iostream>
 
 static void CallbackError(const std::string& message, v8::Local<v8::Function> callback) {
     v8::Local<v8::Value> argv[1] = {Nan::Error(message.c_str())};
@@ -298,10 +299,19 @@ static auto evaluate(mbgl::style::Filter const& filter,
                      mbgl::FeatureType ftype,
                      vtzero::feature const& feature) -> bool // This properties arg is our custom type that we use in our lambda function below.
 {
+    if (!filter.expression) {
+      return true;
+    }
     VTZeroGeometryTileFeature geomfeature(feature, ftype);
-    // std::string const& key is dynamic and comes from the Filter object
-    mbgl::style::expression::EvaluationContext context(zoom, &geomfeature);
-    return filter(context);
+    const mbgl::style::expression::EvaluationResult result = (*filter.expression)->evaluate(context);
+    bool is_error = result.is<mbgl::style::expression::EvaluationError>();
+    if (result) {
+        const mbgl::optional<bool> typed = mbgl::style::expression::fromExpressionValue<bool>(*result);
+        return typed ? *typed : false;
+    } else {
+        std::clog << result.error().message << "\n";
+        return false;
+    }
 }
```

Except that I had to patch gl-native to get `result.is<mbgl::style::expression::EvaluationError>();` to be exposed publicly in the API.

**Comment by springmeyer** [comment]
#47 puts forth a potential solution to this problem without requiring any changes to gl-native.

**Comment by springmeyer** [comment]
noting https://github.com/mapbox/mapbox-gl-js/issues/5234 as historical context for the challenge core to this bug.

**Comment by sofita** [comment]
This looks stale since the PR was closed w.o merge 2 years ago.
